### ISSUE TITLE
multiple `-set-cookie` doesnt work

### ISSUE THREAD

**Issue by mohdaqib57** [sveltejs/realworld#102]
following the guide here https://kit.svelte.dev/docs#routing-endpoints to set multiple cookies (access and refresh token in cookie).

```
To set multiple cookies in a single set of response headers, you can return an array:

return {
	headers: {
		'set-cookie': [cookie1, cookie2]
	}
};
```
it doesnt work

**Comment by benmccann** [comment]
According to https://github.com/sveltejs/kit/issues/3460, this should be fixed in the latest version of SvelteKit. I just bumped the dependencies to the latest (https://github.com/sveltejs/realworld/commit/4cf023ac394274269849824f67903d37897d9ecf). Does it work now?

**Comment by akiarostami** [comment]
It works in endpoints, but unfortunately it still doesn't work for in the hooks. 

```
export const handle = async ({ event, resolve }) => {
	let response = await resolve(event);
	response.headers.set('set-cookie', setCookies); // setCookies is a multi-element array
	return response;
}
```

Only the first item in the `setCookies` array gets assigned.
