### ISSUE TITLE
Launching project causes error

### ISSUE THREAD

**Issue by larrym** [sveltejs/realworld#98]
$ npm run dev
    
    > realworld.svelte.dev@1.0.1-next.0 dev
    > svelte-kit dev
    
    
      SvelteKit v1.0.0-next.151
    
      local:   http://localhost:3000
      network: not exposed
    
      Use --host to expose server to other devices on this network
    
    
    7:43:10 AM [vite-plugin-svelte] /mnt/work/dvp/harris/realworld/src/lib/PreloadingIndicator.svelte:45:1 Unused CSS selector ":global(html).dark .fade"
    <<<<<<<<<< ERROR  >>>>>>>>>>>>>>>>
    Cannot read property 'length' of undefined
    TypeError: Cannot read property 'length' of undefined
        at index.svelte:8:20
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1677:22)
        at eval (/mnt/work/dvp/harris/realworld/src/routes/index.svelte:67:94)
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1677:22)
        at Object.default (root.svelte:39:46)
        at eval (/mnt/work/dvp/harris/realworld/src/routes/__layout.svelte:26:38)
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1677:22)
        at root.svelte:37:44
        at $$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1677:22)
        at Object.render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1685:26)

**Comment by benmccann** [comment]
I can't reproduce this. Maybe try `git clean -xdf` to clear out your project?

Does it work for you with the latest version of SvelteKit?

What OS are you running on?

**Comment by larrym** [comment]
I tried the clean command with the same results. Then I did 'npm update', ran the clean and npm install. Same results. I cloned the repository this morning.

    realworld.svelte.dev@1.0.1-next.0 /mnt/work/dvp/harris/realworld
    ├── @sveltejs/adapter-netlify@1.0.0-next.35
    ├── @sveltejs/adapter-vercel@1.0.0-next.31
    ├── @sveltejs/kit@1.0.0-next.196
    ├── cookie@0.4.1
    ├── marked@2.1.3
    └── svelte@3.44.1
    
    larry@dev22: /mnt/work/dvp/harris/realworld [master]
    $ npm run dev
    
    > realworld.svelte.dev@1.0.1-next.0 dev
    > svelte-kit dev
    
    Pre-bundling dependencies:
      svelte/store
      svelte
      marked
      svelte/animate
      svelte/easing
      (...and 3 more)
    (this will be run only when your dependencies or config have changed)
    
      SvelteKit v1.0.0-next.196
    
      local:   http://localhost:3000
      network: not exposed
    
      Use --host to expose server to other devices on this network
    
    
    9:30:59 AM [vite-plugin-svelte] /mnt/work/dvp/harris/realworld/src/lib/PreloadingIndicator.svelte:45:1 Unused CSS selector ":global(html).dark .fade"
    Cannot read property 'length' of undefined

**Comment by benmccann** [comment]
I just pushed an update with upgraded dependencies. Can you check if it either works or gives you more details in the error message now?

**Comment by larrym** [comment]
Got further, but still crashes.

Sorry, did not answer your question about o/s

    Linux dev22 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Launch window:


    $ npm run dev
    
    > realworld.svelte.dev@1.0.1-next.0 dev
    > svelte-kit dev
    
    Pre-bundling dependencies:
      svelte
      svelte/store
      marked
      svelte/animate
      svelte/easing
      (...and 3 more)
    (this will be run only when your dependencies or config have changed)
    
      SvelteKit v1.0.0-next.230
    
      local:   http://localhost:3000
      network: not exposed
    
      Use --host to expose server to other devices on this network
    
    
    7:54:51 AM [vite-plugin-svelte] /mnt/work/dvp/harris/realworld/src/lib/PreloadingIndicator.svelte:45:1 Unused CSS selector ":global(html).dark .fade"
    `page` in `load` functions has been replaced by `url` and `params`
    Error: `page` in `load` functions has been replaced by `url` and `params`
        at Object.get (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1121:12)
        at load (index.svelte:2:34)
        at load_node (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1131:30)
        at respond$1 (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1345:21)
        at async render_page (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1536:19)
        at async resolve (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1856:10)
        at async Object.handle (//mnt/work/dvp/harris/realworld/src/hooks:7:9)
        at async respond (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1827:10)
        at async file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:2125:24
    $page.path has been replaced by $page.url.pathname
    Error: $page.path has been replaced by $page.url.pathname
        at Object.get (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:627:12)
        at Nav.svelte:10:63
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at eval (/src/routes/__layout.svelte:24:82)
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at root.svelte:38:45
        at $$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at Object.render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1753:26)
        at render_response (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:649:28)
        at async respond$1 (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1457:4)
    $page.path has been replaced by $page.url.pathname
    Error: $page.path has been replaced by $page.url.pathname
        at Object.get (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:627:12)
        at Nav.svelte:10:63
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at eval (/src/routes/__layout.svelte:24:82)
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at root.svelte:38:45
        at $$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at Object.render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1753:26)
        at render_response (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:649:28)
        at async respond_with_error (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1219:10)
    

localhist:3000:

    Error: $page.path has been replaced by $page.url.pathname
        at Object.get (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:627:12)
        at Nav.svelte:10:63
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at eval (/src/routes/__layout.svelte:24:82)
        at Object.$$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at root.svelte:38:45
        at $$render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1745:22)
        at Object.render (/mnt/work/dvp/harris/realworld/node_modules/svelte/internal/index.js:1753:26)
        at render_response (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:649:28)
        at async respond_with_error (file:///mnt/work/dvp/harris/realworld/node_modules/@sveltejs/kit/dist/chunks/index.js:1219:10)

**Comment by larrym** [comment]
Forgot component list:

    realworld.svelte.dev@1.0.1-next.0 /mnt/work/dvp/harris/realworld
    ├── @sveltejs/adapter-netlify@1.0.0-next.38
    ├── @sveltejs/adapter-vercel@1.0.0-next.36
    ├── @sveltejs/kit@1.0.0-next.230
    ├── cookie@0.4.1
    ├── marked@4.0.10
    └── svelte@3.46.2

**Comment by benmccann** [comment]
> Error: $page.path has been replaced by $page.url.pathname

I don't see how you're getting this because I believe I replaced all instances of `page.path` in https://github.com/sveltejs/realworld/commit/a5ddddf7d7ae0603dbbe8357c4b2aec90259ccf3. Can you find one that I missed? I think you are somehow not using the latest code

**Comment by larrym** [comment]
When I updated the project with npm update, it updated all of the
dependencies. I didn't realize you had updated the git repo. My previous
post was referencing hash 77c29bf, not a5dddf. Once I pulled, everything is
fine.

Thanks, Ben, for your patience.
